
#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = hypridle

exec-once = hyprpaper & waybar 
exec-once = nm-applet 
exec-once = blueman-applet
exec-once = kitty & firefox


exec-once = fcitx5 --replace -d
exec-once = export OZONE_PLATFORM_HINT=auto
