
################
### MONITORS ###
################

# See https://wiki.hyprland.org/Configuring/Monitors/
# monitor = eDP-1,2880x1920@120, auto, auto


monitor = eDP-1 , 2880x1920@120 , 0x0 , 2

monitor = , highres , auto-up , 2

# others , , DP-2
# preferred , highres , highrr
# auto , auto-right , auto-up

# See https://wiki.hyprland.org/Configuring/Monitors/

# preferred highrr highres

#monitor = DP-2 , 1920x1080 , 1440x0 , auto
