unbind C-b
set -g prefix C-b

unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

set -g extended-keys on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
set -g @dracula-show-left-icon session
set -g @dracula-show-fahrenheit false
set -g @deacula-show-timezone false
set -g @dracula-time-format "%F %R"

# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, tmux-ram-usage, network, network-bandwidth, network-ping, ssh-session, attached-clients, network-vpn, weather, time, mpc, spotify-tui, playerctl, kubernetes-context, synchronize-panes
set -g @dracula-plugins "git battery network cpu-usage ram-usage time"

#set -g @dracula-plugins "git time"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
