# vim:ft=kitty

background_opacity 0.8
window_padding_width 5

# BEGIN_CURSOR

cursor #34DD9A
cursor_shape beam
cursor_beam_thickness 2
cursor_trail 5
cursor_trail_decay 0.1 0.5


# END_CURSOR\

# BEGIN_KITTY_FONTS
font_family      family="FiraCode Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 10.0
# END_KITTY_FONTS\

term xterm-256color
